"""baseline schema

Revision ID: ad674b51adca
Revises: 
Create Date: 2026-07-31 03:03:12.540478
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad674b51adca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_appmodels',
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('invariants', sa.JSON(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('idempotency', sa.JSON(), nullable=False),
    sa.Column('out_of_scope_rules', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('app_id', 'version')
    )
    op.create_index(op.f('ix_core_appmodels_status'), 'core_appmodels', ['status'], unique=False)
    op.create_table('core_asset_nodes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_asset_nodes_asset_type'), 'core_asset_nodes', ['asset_type'], unique=False)
    op.create_table('core_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_audit_events_event_hash'), 'core_audit_events', ['event_hash'], unique=False)
    op.create_table('core_bundle_activations',
    sa.Column('singleton', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('active_bundle_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('singleton')
    )
    op.create_table('core_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('schema', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('min_engine_version', sa.String(length=16), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.Column('assertions', sa.JSON(), nullable=False),
    sa.Column('evidence_req', sa.JSON(), nullable=False),
    sa.Column('cwe', sa.JSON(), nullable=False),
    sa.Column('cve', sa.JSON(), nullable=False),
    sa.Column('owasp', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_cases_status'), 'core_cases', ['status'], unique=False)
    op.create_table('core_coverage_matrices',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('mappings', sa.JSON(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('version', 'framework')
    )
    op.create_index(op.f('ix_core_coverage_matrices_digest'), 'core_coverage_matrices', ['digest'], unique=False)
    op.create_table('core_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('sha256', sa.String(length=80), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_evidence_sha256'), 'core_evidence', ['sha256'], unique=False)
    op.create_table('core_findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('asset', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cwe', sa.JSON(), nullable=False),
    sa.Column('cve', sa.JSON(), nullable=False),
    sa.Column('owasp', sa.JSON(), nullable=False),
    sa.Column('observation_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('oracle_verdict', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_findings_assessment_id'), 'core_findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_core_findings_fingerprint'), 'core_findings', ['fingerprint'], unique=False)
    op.create_table('core_intel_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cursor', sa.String(length=128), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_intel_snapshots_source'), 'core_intel_snapshots', ['source'], unique=False)
    op.create_table('core_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_step_key', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_digest', sa.String(length=80), nullable=False),
    sa.Column('failure_class', sa.String(length=32), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_jobs_idempotency_key'), 'core_jobs', ['idempotency_key'], unique=True)
    op.create_table('core_projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('coverage_rate', sa.Float(), nullable=False),
    sa.Column('completeness_ok', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_reports_assessment_id'), 'core_reports', ['assessment_id'], unique=False)
    op.create_table('core_test_catalogs',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('mappings', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_index(op.f('ix_core_test_catalogs_digest'), 'core_test_catalogs', ['digest'], unique=False)
    op.create_table('core_update_bundles',
    sa.Column('bundle_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('staged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bundle_id')
    )
    op.create_index(op.f('ix_core_update_bundles_version'), 'core_update_bundles', ['version'], unique=False)
    op.create_table('core_vulnerabilities',
    sa.Column('canonical_id', sa.String(length=64), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cvss', sa.JSON(), nullable=False),
    sa.Column('cwe', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index(op.f('ix_core_vulnerabilities_digest'), 'core_vulnerabilities', ['digest'], unique=False)
    op.create_table('core_affected_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vulnerability_id', sa.String(length=64), nullable=False),
    sa.Column('vendor', sa.String(length=256), nullable=False),
    sa.Column('product', sa.String(length=256), nullable=False),
    sa.Column('cpe', sa.String(length=256), nullable=True),
    sa.Column('package', sa.String(length=256), nullable=True),
    sa.Column('version_range', sa.String(length=256), nullable=False),
    sa.Column('fixed_versions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['core_vulnerabilities.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_affected_products_vulnerability_id'), 'core_affected_products', ['vulnerability_id'], unique=False)
    op.create_table('core_asset_edges',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('src_id', sa.String(length=128), nullable=False),
    sa.Column('dst_id', sa.String(length=128), nullable=False),
    sa.Column('rel', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['core_asset_nodes.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['core_asset_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_asset_edges_src_id'), 'core_asset_edges', ['src_id'], unique=False)
    op.create_table('core_detection_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vulnerability_id', sa.String(length=64), nullable=False),
    sa.Column('case_version', sa.String(length=64), nullable=False),
    sa.Column('detection_type', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['core_vulnerabilities.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_detection_mappings_vulnerability_id'), 'core_detection_mappings', ['vulnerability_id'], unique=False)
    op.create_table('core_exploitation_signals',
    sa.Column('vulnerability_id', sa.String(length=64), nullable=False),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=False),
    sa.Column('public_exploit', sa.Boolean(), nullable=False),
    sa.Column('ransomware', sa.Boolean(), nullable=False),
    sa.Column('active_exploitation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['core_vulnerabilities.canonical_id'], ),
    sa.PrimaryKeyConstraint('vulnerability_id')
    )
    op.create_table('core_scope_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('include', sa.JSON(), nullable=False),
    sa.Column('exclude', sa.JSON(), nullable=False),
    sa.Column('ports', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['core_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_scope_snapshots_digest'), 'core_scope_snapshots', ['digest'], unique=False)
    op.create_table('core_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('scope_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_plan_id', sa.String(length=64), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core_projects.id'], ),
    sa.ForeignKeyConstraint(['scope_snapshot_id'], ['core_scope_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('plan_digest', sa.String(length=80), nullable=False),
    sa.Column('scope_digest', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('approved_risks', sa.JSON(), nullable=False),
    sa.Column('approved_capabilities', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['core_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_approvals_digest'), 'core_approvals', ['digest'], unique=False)
    op.create_table('core_execution_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['core_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_execution_plans_digest'), 'core_execution_plans', ['digest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_execution_plans_digest'), table_name='core_execution_plans')
    op.drop_table('core_execution_plans')
    op.drop_index(op.f('ix_core_approvals_digest'), table_name='core_approvals')
    op.drop_table('core_approvals')
    op.drop_table('core_assessments')
    op.drop_index(op.f('ix_core_scope_snapshots_digest'), table_name='core_scope_snapshots')
    op.drop_table('core_scope_snapshots')
    op.drop_table('core_exploitation_signals')
    op.drop_index(op.f('ix_core_detection_mappings_vulnerability_id'), table_name='core_detection_mappings')
    op.drop_table('core_detection_mappings')
    op.drop_index(op.f('ix_core_asset_edges_src_id'), table_name='core_asset_edges')
    op.drop_table('core_asset_edges')
    op.drop_index(op.f('ix_core_affected_products_vulnerability_id'), table_name='core_affected_products')
    op.drop_table('core_affected_products')
    op.drop_index(op.f('ix_core_vulnerabilities_digest'), table_name='core_vulnerabilities')
    op.drop_table('core_vulnerabilities')
    op.drop_index(op.f('ix_core_update_bundles_version'), table_name='core_update_bundles')
    op.drop_table('core_update_bundles')
    op.drop_index(op.f('ix_core_test_catalogs_digest'), table_name='core_test_catalogs')
    op.drop_table('core_test_catalogs')
    op.drop_index(op.f('ix_core_reports_assessment_id'), table_name='core_reports')
    op.drop_table('core_reports')
    op.drop_table('core_projects')
    op.drop_index(op.f('ix_core_jobs_idempotency_key'), table_name='core_jobs')
    op.drop_table('core_jobs')
    op.drop_index(op.f('ix_core_intel_snapshots_source'), table_name='core_intel_snapshots')
    op.drop_table('core_intel_snapshots')
    op.drop_index(op.f('ix_core_findings_fingerprint'), table_name='core_findings')
    op.drop_index(op.f('ix_core_findings_assessment_id'), table_name='core_findings')
    op.drop_table('core_findings')
    op.drop_index(op.f('ix_core_evidence_sha256'), table_name='core_evidence')
    op.drop_table('core_evidence')
    op.drop_index(op.f('ix_core_coverage_matrices_digest'), table_name='core_coverage_matrices')
    op.drop_table('core_coverage_matrices')
    op.drop_index(op.f('ix_core_cases_status'), table_name='core_cases')
    op.drop_table('core_cases')
    op.drop_table('core_bundle_activations')
    op.drop_index(op.f('ix_core_audit_events_event_hash'), table_name='core_audit_events')
    op.drop_table('core_audit_events')
    op.drop_index(op.f('ix_core_asset_nodes_asset_type'), table_name='core_asset_nodes')
    op.drop_table('core_asset_nodes')
    op.drop_index(op.f('ix_core_appmodels_status'), table_name='core_appmodels')
    op.drop_table('core_appmodels')
    # ### end Alembic commands ###
