from __future__ import annotations
from typing import Protocol
from ...domain.assessments.models import Assessment, ExecutionPlan, Approval
from ...domain.audit.models import AuditEvent
from ...domain.projects.models import Project
from ...domain.scope.models import ScopeSnapshot


class ProjectRepository(Protocol):
    def add(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...


class ScopeRepository(Protocol):
    def add_snapshot(self, snapshot: ScopeSnapshot) -> None: ...
    def get_snapshot(self, snapshot_id: str) -> ScopeSnapshot | None: ...


class AssessmentRepository(Protocol):
    def add(self, assessment: Assessment) -> None: ...
    def get(self, assessment_id: str) -> Assessment | None: ...
    def save_plan(self, plan: ExecutionPlan) -> None: ...
    def get_plan(self, plan_id: str) -> ExecutionPlan | None: ...
    def save_approval(self, approval: Approval) -> None: ...


class AuditRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def list_events(self) -> list[AuditEvent]: ...
    def last_hash(self) -> str: ...
