/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scopes/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze Scope */
        post: operations["freeze_scope_scopes_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scopes/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scope */
        get: operations["get_scope_scopes__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessments */
        get: operations["list_assessments_assessments_get"];
        put?: never;
        /** Create Assessment */
        post: operations["create_assessment_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Plan
         * @description Deterministically generate the execution plan for an assessment (decision F).
         *
         *     The Planner turns the pinned TestCatalog's required classes for the scope's
         *     asset types into a risk-tiered DAG (recon before active before intrusive).
         *     The plan is attached to the assessment, which moves to awaiting_approval.
         *     Generation is a pure function of catalog + scope - never the LLM.
         */
        post: operations["generate_plan_assessments__assessment_id__plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_findings_get"];
        put?: never;
        /** Create Finding */
        post: operations["create_finding_findings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Finding */
        get: operations["get_finding_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{finding_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Verdict
         * @description Record the oracle's N/N reproduction verdict on a finding.
         *
         *     The verdict is written by the deterministic oracle (internal, via the
         *     application layer) or a human manual override. An agent may never set a
         *     finding's verdict - confirming/refuting findings is forbidden to the LLM
         *     (LLM boundary).
         */
        post: operations["set_verdict_findings__finding_id__verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intel/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Intel */
        get: operations["search_intel_intel_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intel/{canonical_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vulnerability */
        get: operations["get_vulnerability_intel__canonical_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Bundle */
        get: operations["get_active_bundle_updates_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/bundles/{bundle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bundle */
        get: operations["get_bundle_updates_bundles__bundle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Chain */
        get: operations["verify_chain_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Approvals */
        get: operations["pending_approvals_approvals_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval History */
        get: operations["approval_history_approvals_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Approval */
        post: operations["create_approval_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Approval */
        post: operations["reject_approval_approvals_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset Graph */
        get: operations["get_asset_graph_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        /**
         * Update Case Yaml
         * @description Update a case's YAML source (CaseStudio Monaco editor).
         *
         *     Only unsigned cases (DRAFT/VALIDATED) are editable; SIGNED/PUBLISHED cases
         *     are immutable (immutability after signing).
         */
        put: operations["update_case_yaml_cases__case_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Case */
        post: operations["validate_case_cases__case_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Case
         * @description Deterministic risk/schema analysis for the YAML editor (no transition).
         *
         *     Runs the RiskAnalyzer over the case and reports the declared-vs-computed
         *     risk so the CaseStudio editor can preview risk and block publish on a
         *     mismatch. This is static analysis - nothing is executed, and the LLM is
         *     never involved.
         */
        post: operations["analyze_case_cases__case_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Case */
        post: operations["review_case_cases__case_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Case */
        post: operations["sign_case_cases__case_id__sign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Case */
        post: operations["publish_case_cases__case_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appmodels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List App Models */
        get: operations["list_app_models_appmodels_get"];
        put?: never;
        /** Create App Model */
        post: operations["create_app_model_appmodels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appmodels/{app_id}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Model */
        get: operations["get_app_model_appmodels__app_id___version__get"];
        /**
         * Update App Model
         * @description Edit a model in place (only DRAFT/HUMAN_VALIDATED; signed -> revise).
         */
        put: operations["update_app_model_appmodels__app_id___version__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appmodels/{app_id}/{version}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revise App Model
         * @description Create a new DRAFT version (version bump) from the edited content.
         */
        post: operations["revise_app_model_appmodels__app_id___version__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appmodels/{app_id}/{version}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate App Model */
        post: operations["validate_app_model_appmodels__app_id___version__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appmodels/{app_id}/{version}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign App Model */
        post: operations["sign_app_model_appmodels__app_id___version__sign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appmodels/{app_id}/{version}/generate-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Tests
         * @description Deterministically generate logic-test cases from a SIGNED AppModel.
         *
         *     Generation is a pure function of the signed model (never the LLM). Each
         *     LogicTestCase is wrapped as a model-generated case and advanced through the
         *     case fast path (auto risk-gate; ACTIVE cases stop at VALIDATED pending human
         *     review). Idempotent: the same model yields the same case signatures.
         */
        post: operations["generate_tests_appmodels__app_id___version__generate_tests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signing-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signing Keys */
        get: operations["list_signing_keys_signing_keys_get"];
        put?: never;
        /** Create Signing Key */
        post: operations["create_signing_key_signing_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessment_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assessment Events
         * @description Stream assessment status as server-sent events (long task).
         */
        get: operations["assessment_events_assessments__assessment_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveBundleOut */
        ActiveBundleOut: {
            /** Active Bundle Id */
            active_bundle_id: string | null;
            bundle: components["schemas"]["UpdateBundleOut"] | null;
        };
        /** AffectedProductOut */
        AffectedProductOut: {
            /** Vendor */
            vendor: string;
            /** Product */
            product: string;
            /** Cpe */
            cpe: string | null;
            /** Package */
            package: string | null;
            /** Version Range */
            version_range: string;
            /** Fixed Versions */
            fixed_versions: string[];
        };
        /** AppModelCreate */
        AppModelCreate: {
            /** App Id */
            app_id: string;
            /** Version */
            version: string;
            /** States */
            states: string[];
            /**
             * Transitions
             * @default []
             */
            transitions: components["schemas"]["TransitionIn"][];
            /**
             * Invariants
             * @default []
             */
            invariants: components["schemas"]["InvariantIn"][];
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldIn"][];
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["RoleIn"][];
            /**
             * Out Of Scope Rules
             * @default []
             */
            out_of_scope_rules: string[];
            /**
             * Llm Proposed
             * @default false
             */
            llm_proposed: boolean;
        };
        /** AppModelOut */
        AppModelOut: {
            /** App Id */
            app_id: string;
            /** Version */
            version: string;
            /** States */
            states: string[];
            /** Transitions */
            transitions: components["schemas"]["TransitionOut"][];
            /** Invariants */
            invariants: components["schemas"]["InvariantOut"][];
            /** Fields */
            fields: components["schemas"]["FieldOut"][];
            /** Roles */
            roles: components["schemas"]["RoleOut"][];
            /** Out Of Scope Rules */
            out_of_scope_rules: string[];
            /** Status */
            status: string;
            /** Digest */
            digest: string;
            /** Signature */
            signature: string | null;
        };
        /** AppModelRevise */
        AppModelRevise: {
            /** App Id */
            app_id: string;
            /** Version */
            version: string;
            /** States */
            states: string[];
            /**
             * Transitions
             * @default []
             */
            transitions: components["schemas"]["TransitionIn"][];
            /**
             * Invariants
             * @default []
             */
            invariants: components["schemas"]["InvariantIn"][];
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldIn"][];
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["RoleIn"][];
            /**
             * Out Of Scope Rules
             * @default []
             */
            out_of_scope_rules: string[];
            /**
             * Llm Proposed
             * @default false
             */
            llm_proposed: boolean;
            /** New Version */
            new_version?: string | null;
        };
        /** ApprovalCreate */
        ApprovalCreate: {
            /** Assessment Id */
            assessment_id: string;
            /** Approved By */
            approved_by: string;
            /**
             * Approved Risks
             * @default []
             */
            approved_risks: string[];
            /**
             * Approved Capabilities
             * @default []
             */
            approved_capabilities: string[];
            /**
             * Actor Role
             * @default human
             */
            actor_role: string;
        };
        /**
         * ApprovalDecisionOut
         * @description A decided approval (approved or rejected).
         */
        ApprovalDecisionOut: {
            /** Assessment Id */
            assessment_id: string;
            /** Project Id */
            project_id: string;
            /** Decision */
            decision: string;
            /** Decided By */
            decided_by: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Approved Risks
             * @default []
             */
            approved_risks: string[];
            /**
             * Approved Capabilities
             * @default []
             */
            approved_capabilities: string[];
            /**
             * Plan Digest
             * @default
             */
            plan_digest: string;
            /**
             * Scope Digest
             * @default
             */
            scope_digest: string;
        };
        /** ApprovalOut */
        ApprovalOut: {
            /** Id */
            id: string;
            /** Assessment Id */
            assessment_id: string;
            /** Plan Digest */
            plan_digest: string;
            /** Scope Digest */
            scope_digest: string;
            /** Mode */
            mode: string;
            /** Approved Risks */
            approved_risks: string[];
            /** Approved Capabilities */
            approved_capabilities: string[];
            /** Approved By */
            approved_by: string;
            /** Digest */
            digest: string;
        };
        /** ApprovalReject */
        ApprovalReject: {
            /** Assessment Id */
            assessment_id: string;
            /** Rejected By */
            rejected_by: string;
            /** Reason */
            reason: string;
            /**
             * Actor Role
             * @default human
             */
            actor_role: string;
        };
        /**
         * ApprovalRequestOut
         * @description A pending approval: an assessment awaiting a human decision.
         */
        ApprovalRequestOut: {
            /** Assessment Id */
            assessment_id: string;
            /** Project Id */
            project_id: string;
            /** Mode */
            mode: string;
            /** Plan Id */
            plan_id: string | null;
            /** Plan Digest */
            plan_digest: string | null;
            /** Scope Digest */
            scope_digest: string | null;
        };
        /** AssessmentCreate */
        AssessmentCreate: {
            /** Project Id */
            project_id: string;
            /** Scope Snapshot Id */
            scope_snapshot_id: string;
            /**
             * Mode
             * @default approval
             */
            mode: string;
        };
        /** AssessmentOut */
        AssessmentOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Scope Snapshot Id */
            scope_snapshot_id: string;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Active Plan Id */
            active_plan_id?: string | null;
            /** Approval Id */
            approval_id?: string | null;
        };
        /** AssetEdgeOut */
        AssetEdgeOut: {
            src: components["schemas"]["AssetNodeOut"];
            dst: components["schemas"]["AssetNodeOut"];
            /** Rel */
            rel: string;
        };
        /** AssetGraphOut */
        AssetGraphOut: {
            /** Nodes */
            nodes: components["schemas"]["AssetNodeOut"][];
            /** Edges */
            edges: components["schemas"]["AssetEdgeOut"][];
        };
        /** AssetNodeOut */
        AssetNodeOut: {
            /** Type */
            type: string;
            /** Value */
            value: string;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Id */
            id: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Previous Hash */
            previous_hash: string;
            /** Event Hash */
            event_hash: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** AuditVerifyOut */
        AuditVerifyOut: {
            /** Valid */
            valid: boolean;
            /** Event Count */
            event_count: number;
        };
        /** CaseAction */
        CaseAction: {
            /**
             * Actor Role
             * @default human
             */
            actor_role: string;
            /** Key Id */
            key_id?: string | null;
        };
        /**
         * CaseAnalysisOut
         * @description Read-only risk/schema analysis for the CaseStudio YAML editor (decision D).
         *
         *     Computed by the deterministic RiskAnalyzer (never the LLM): ``computed_risk``
         *     is None when a deny-listed pattern is present; ``risk_ok`` is True when the
         *     declared risk is >= the computed risk.
         */
        CaseAnalysisOut: {
            /** Case Id */
            case_id: string;
            /** Declared Risk */
            declared_risk: string;
            /** Computed Risk */
            computed_risk: string | null;
            /** Denied */
            denied: boolean;
            /** Risk Ok */
            risk_ok: boolean;
            /** Schema Ok */
            schema_ok: boolean;
            /** Errors */
            errors: string[];
        };
        /** CaseCreate */
        CaseCreate: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Author */
            author: string;
            /** Risk */
            risk: string;
            /** Target Type */
            target_type: string;
            /** Case Schema */
            case_schema: string;
            /** Steps */
            steps: components["schemas"]["CaseStepIn"][];
            /**
             * Cwe
             * @default []
             */
            cwe: string[];
            /**
             * Cve
             * @default []
             */
            cve: string[];
            /**
             * Owasp
             * @default []
             */
            owasp: string[];
            /**
             * Origin
             * @default manual
             */
            origin: string;
            /**
             * Yaml
             * @default
             */
            yaml: string;
        };
        /** CaseOut */
        CaseOut: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Author */
            author: string;
            /** Risk */
            risk: string;
            /** Target Type */
            target_type: string;
            /** Case Schema */
            case_schema: string;
            /** Status */
            status: string;
            /** Origin */
            origin: string;
            /** Signature */
            signature: string;
            /** Steps */
            steps: components["schemas"]["CaseStepOut"][];
            /** Cwe */
            cwe: string[];
            /** Cve */
            cve: string[];
            /** Owasp */
            owasp: string[];
            /** Yaml */
            yaml: string;
        };
        /** CaseStepIn */
        CaseStepIn: {
            /** Id */
            id: string;
            /** Action */
            action: string;
            /**
             * Spec
             * @default {}
             */
            spec: {
                [key: string]: unknown;
            };
        };
        /** CaseStepOut */
        CaseStepOut: {
            /** Id */
            id: string;
            /** Action */
            action: string;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** CaseYamlUpdate */
        CaseYamlUpdate: {
            /** Yaml */
            yaml: string;
        };
        /** CreateSigningKey */
        CreateSigningKey: {
            /** Name */
            name: string;
            /**
             * Actor Role
             * @default human
             */
            actor_role: string;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Id */
            id: string;
            /** Layer */
            layer: string;
            /** Sha256 */
            sha256: string;
            /** Storage Uri */
            storage_uri: string;
            /** Source Id */
            source_id: string;
            /** Signature */
            signature: string;
        };
        /** ExploitationSignalOut */
        ExploitationSignalOut: {
            /** Kev */
            kev: boolean;
            /** Epss Score */
            epss_score: number;
            /** Public Exploit */
            public_exploit: boolean;
            /** Ransomware */
            ransomware: boolean;
            /** Active Exploitation */
            active_exploitation: boolean;
        };
        /** FieldIn */
        FieldIn: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Range */
            range?: unknown[] | null;
            /**
             * Trusted Source
             * @default client
             */
            trusted_source: string;
        };
        /** FieldOut */
        FieldOut: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Range */
            range: unknown[] | null;
            /** Trusted Source */
            trusted_source: string;
        };
        /** FindingCreate */
        FindingCreate: {
            /** Title */
            title: string;
            /** Asset */
            asset: string;
            /**
             * Severity
             * @default medium
             */
            severity: string;
            /**
             * Cwe
             * @default []
             */
            cwe: string[];
            /**
             * Assessment Id
             * @default
             */
            assessment_id: string;
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Title */
            title: string;
            /** Asset */
            asset: string;
            /** Severity */
            severity: string;
            /** Cwe */
            cwe: string[];
            /** Cve */
            cve: string[];
            /** Owasp */
            owasp: string[];
            /** Status */
            status: string;
            /** Assessment Id */
            assessment_id: string;
            /** Oracle Verdict */
            oracle_verdict: string;
        };
        /** FindingVerdict */
        FindingVerdict: {
            /** Verdict */
            verdict: string;
            /**
             * Actor Role
             * @default human
             */
            actor_role: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvariantIn */
        InvariantIn: {
            /** Id */
            id: string;
            /** Expr */
            expr: string;
        };
        /** InvariantOut */
        InvariantOut: {
            /** Id */
            id: string;
            /** Expr */
            expr: string;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Plan Step Key */
            plan_step_key: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Status */
            status: string;
            /** Attempt */
            attempt: number;
            /** Max Attempts */
            max_attempts: number;
            /** Lease Owner */
            lease_owner: string | null;
            /** Result Digest */
            result_digest: string;
            /** Failure Class */
            failure_class: string;
            /** Dependencies */
            dependencies: string[];
        };
        /** PlanCreate */
        PlanCreate: {
            /** Assessment Id */
            assessment_id: string;
            /** Steps */
            steps: components["schemas"]["PlanStepIn"][];
        };
        /** PlanOut */
        PlanOut: {
            /** Id */
            id: string;
            /** Assessment Id */
            assessment_id: string;
            /** Version */
            version: number;
            /** Digest */
            digest: string;
            /** Steps */
            steps: components["schemas"]["PlanStepOut"][];
        };
        /** PlanStepIn */
        PlanStepIn: {
            /** Key */
            key: string;
            /** Runner */
            runner: string;
            /** Risk */
            risk: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Dependencies
             * @default []
             */
            dependencies: string[];
        };
        /** PlanStepOut */
        PlanStepOut: {
            /** Key */
            key: string;
            /** Runner */
            runner: string;
            /** Risk */
            risk: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Dependencies */
            dependencies: string[];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReportOut */
        ReportOut: {
            /** Id */
            id: string;
            /** Assessment Id */
            assessment_id: string;
            /** Title */
            title: string;
            /** Sections */
            sections: components["schemas"]["ReportSectionOut"][];
            /** Finding Count */
            finding_count: number;
            /** Coverage Rate */
            coverage_rate: number;
            /** Completeness Ok */
            completeness_ok: boolean;
            /** Status */
            status: string;
            /** Digest */
            digest: string;
        };
        /** ReportSectionOut */
        ReportSectionOut: {
            /** Name */
            name: string;
            /** Content */
            content: string;
        };
        /** RoleIn */
        RoleIn: {
            /** Id */
            id: string;
            /**
             * Capabilities
             * @default []
             */
            capabilities: string[];
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: string;
            /** Capabilities */
            capabilities: string[];
        };
        /** ScopeDraftCreate */
        ScopeDraftCreate: {
            /** Project Id */
            project_id: string;
            /** Include */
            include: string[];
            /**
             * Exclude
             * @default []
             */
            exclude: string[];
            /**
             * Ports
             * @default [
             *       80,
             *       443
             *     ]
             */
            ports: number[];
            /**
             * Approved By
             * @default analyst
             */
            approved_by: string;
            /**
             * Requests Per Second
             * @default 5
             */
            requests_per_second: number;
            /**
             * Concurrency
             * @default 3
             */
            concurrency: number;
            /**
             * Max Requests
             * @default 50000
             */
            max_requests: number;
        };
        /** ScopeLimitsOut */
        ScopeLimitsOut: {
            /** Requests Per Second */
            requests_per_second: number;
            /** Concurrency */
            concurrency: number;
            /** Max Requests */
            max_requests: number;
        };
        /** ScopeSnapshotOut */
        ScopeSnapshotOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Include */
            include: string[];
            /** Exclude */
            exclude: string[];
            /** Ports */
            ports: number[];
            /** Cloud Accounts */
            cloud_accounts: string[];
            limits: components["schemas"]["ScopeLimitsOut"];
            /** Approved By */
            approved_by: string;
            /** Digest */
            digest: string;
        };
        /** SigningKeyOut */
        SigningKeyOut: {
            /** Key Id */
            key_id: string;
            /** Name */
            name: string;
            /** Public Key */
            public_key: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ToolOut */
        ToolOut: {
            /** Key */
            key: string;
            /** Image */
            image: string;
            /** Tag */
            tag: string;
            /** Digest */
            digest: string;
            /** Domain */
            domain: string;
        };
        /** TransitionIn */
        TransitionIn: {
            /** Id */
            id: string;
            /** From State */
            from_state: string;
            /** To State */
            to_state: string;
            /** Endpoint */
            endpoint: string;
            /**
             * Params
             * @default []
             */
            params: string[];
            /**
             * Idempotent
             * @default false
             */
            idempotent: boolean;
        };
        /** TransitionOut */
        TransitionOut: {
            /** Id */
            id: string;
            /** From State */
            from_state: string;
            /** To State */
            to_state: string;
            /** Endpoint */
            endpoint: string;
            /** Params */
            params: string[];
            /** Idempotent */
            idempotent: boolean;
        };
        /** UpdateBundleOut */
        UpdateBundleOut: {
            /** Bundle Id */
            bundle_id: string;
            /** Version */
            version: string;
            /** Digest */
            digest: string;
            /** Staged At */
            staged_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VulnerabilityOut */
        VulnerabilityOut: {
            /** Canonical Id */
            canonical_id: string;
            /** Aliases */
            aliases: string[];
            /** Description */
            description: string;
            /** Cvss */
            cvss: {
                [key: string]: number;
            };
            /** Cwe */
            cwe: string[];
            /** References */
            references: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Affected Products */
            affected_products: components["schemas"]["AffectedProductOut"][];
            exploitation_signal: components["schemas"]["ExploitationSignalOut"];
            /** Digest */
            digest: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freeze_scope_scopes_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeDraftCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scope_scopes__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments_assessments_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assessment_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_assessments__assessment_id__plans_post: {
        parameters: {
            query?: {
                catalog_version?: string | null;
            };
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolOut"][];
                };
            };
        };
    };
    list_findings_findings_get: {
        parameters: {
            query?: {
                assessment_id?: string | null;
                severity?: string | null;
                oracle_verdict?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_finding_findings_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finding_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_verdict_findings__finding_id__verdict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingVerdict"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_intel_intel_search_get: {
        parameters: {
            query?: {
                keyword?: string | null;
                cve?: string | null;
                cwe?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vulnerability_intel__canonical_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canonical_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_bundle_updates_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveBundleOut"];
                };
            };
        };
    };
    get_bundle_updates_bundles__bundle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateBundleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_audit_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
        };
    };
    verify_chain_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyOut"];
                };
            };
        };
    };
    create_plan_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_approvals_approvals_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequestOut"][];
                };
            };
        };
    };
    approval_history_approvals_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionOut"][];
                };
            };
        };
    };
    create_approval_approvals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_approval_approvals_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalReject"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_graph_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetGraphOut"];
                };
            };
        };
    };
    list_evidence_evidence_get: {
        parameters: {
            query?: {
                finding_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_reports_get: {
        parameters: {
            query: {
                assessment_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
        };
    };
    create_case_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_yaml_cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseYamlUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_case_cases__case_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_case_cases__case_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_case_cases__case_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_case_cases__case_id__sign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_case_cases__case_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_app_models_appmodels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"][];
                };
            };
        };
    };
    create_app_model_appmodels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_model_appmodels__app_id___version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_app_model_appmodels__app_id___version__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_app_model_appmodels__app_id___version__revise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppModelRevise"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_app_model_appmodels__app_id___version__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_app_model_appmodels__app_id___version__sign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_tests_appmodels__app_id___version__generate_tests_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_signing_keys_signing_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningKeyOut"][];
                };
            };
        };
    };
    create_signing_key_signing_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSigningKey"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    assessment_events_assessments__assessment_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
